name: CI pipeline
on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: install dependencies
        run: npm install

      - name: run docker container
        run: |
          docker build -t hello-api .
          docker run -d -p 3000:3000 --name hello-api hello-api
          sleep 5
          curl http://localhost:3000/hello     
