name: CI pipeline
on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: install dependencies
        run: npm install


      - name: build docker image
        run: docker build -t hello-api .

      - name: tag image
        run: docker tag hello-api localhost:5000/hello-api:v2

      - name: push image
        run: docker push localhost:5000/hello-api:v2

      - name: run docker container
        run: |
          docker run -d -p 3000:3000 --name hello-api localhost:5000/hello-api:v2
          sleep 5
          curl http://localhost:3000/hello     
