name: CI pipeline
on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: install dependencies
        run: npm install

      - name: test
        run: |
          node app/server.js &
          sleep 5 
          curl http://localhost:3000/hello 

      - name: build docker image
        run: docker build --no-cache -t hello-api .


      - name: start local registry
        run: docker run -d -p 5000:5000 --name registry registry:2

      - name: tag image
        run: docker tag hello-api ${{secrets.ECR_URL}}/hello-api:v3

      - name: push image
        run: docker push ${{secrets.ECR_URL}}/hello-api:v3
   
      - name: delete old container
        run: docker rm -f hello-api|| true

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: Check cluster
        run: |
          kubectl get nodes

      - name: deploy to kubernetes
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
          kubectl apply -f kubernetes/ingress.yaml
        
      - name: Test DNS
        run: |
          nslookup node.example.com
          ping -c 3 node.example.com
              
